blog/urls.py
"""
this script is used to create the models for the projects app.

Author: reza
date: 6/28/2020
"""
from django.urls import path
from . views import ArticleList, ArticleDetail, CategoryList, AuthorList, ArticlePreview


app_name = 'blog'
urlpatterns = [
       path('', ArticleList.as_view(), name="home"),
       path('page/<int:page>', ArticleList.as_view(), name="home"),
       path('post/<slug:slug>', ArticleDetail.as_view(), name="detail_article"),
       path('preview/<int:pk>', ArticlePreview.as_view(), name="preview_article"),
       path('category/<slug:slug>', CategoryList.as_view(), name="catelist"),
       path('category/<slug:slug>/page/<int:page>', CategoryList.as_view(), name="catelist"),
       path('author/<slug:username>', AuthorList.as_view(), name="author"),
       path('author/<slug:username>/page/<int:page>', AuthorList.as_view(), name="author")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from account.models import User
from django.utils import timezone
from django.utils.html import format_html
from extensions.utils import jalali_convert, peersian_time
# ----->

# my Managers
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status='p')

class CategoryManager(models.Manager):
    def active(self):
        return self.filter(status=True)

# Category Model
class Category(models.Model):
    parent = models.ForeignKey('self', default = None, null=True, blank=True,on_delete=models.SET_NULL, related_name='children',verbose_name='زیردسته')
    title = models.CharField(max_length=200, verbose_name='سرنام دسته‌بندی')
    slug = models.SlugField(max_length=100, unique=True, verbose_name='نامک دسته‌بندی')
    status = models.BooleanField(default=True, verbose_name="آیا نمایش داده شود؟")
    posision = models.IntegerField(verbose_name="چیدمان")
    class Meta:
        verbose_name = 'دسته‌بندی'
        verbose_name_plural = 'دسته‌بندی ها'
        ordering = ['parent__id', 'posision']

    def __str__(self):
        return self.title
    objects = CategoryManager()
    
# ----->

#  Article Model
class Article(models.Model):
    STATUS_CHOICES = (
        ('d','پیش‌نویس'),
        ('p','نمایش داده شده'),
    )
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='articles', verbose_name='نویسنده')
    category = models.ManyToManyField(Category, verbose_name = 'دسته‌بندی', related_name="articles")
    title = models.CharField(max_length=200, verbose_name ='سرنام')
    slug = models.SlugField(max_length=100,unique=True, verbose_name ='نامک')
    body = models.TextField(verbose_name ='نوشته')
    thumbnail = models.ImageField(upload_to='images', verbose_name ='فرتور')
    publish = models.DateTimeField(default=timezone.now,verbose_name ='تاریخ نمایش')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=1,choices=STATUS_CHOICES, verbose_name ='وضعیت')


    class Meta:
        verbose_name = 'نگاشت'
        verbose_name_plural = 'نگاشت ها'
        ordering = ['-publish']


    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("account:home")

    def jpublish(self):
        return jalali_convert(self.publish)
    
    def jTimepublish(self):
        return peersian_time(self.publish)    
    jpublish.short_description = 'تاریخ انتشار'

    def thumbnail_tag(self):
        return format_html("<img style='width:100px; height:50px;border-radius:5px;' src='{}'>".format(self.thumbnail.url))

    def category_to_str(self):
        return "، ".join([category.title for category in self.category.active()])
    
    category_to_str.short_description = 'دسته‌بندی'
    
    objects = ArticleManager()
# ----->

blog/views.py
"""
this script is used to create the models for the projects app.

Author: reza
date: 6/28/2020
"""
from django.core.paginator import Paginator
from account.models import User
from django.views.generic import ListView, DetailView
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from .models import Article, Category
from account.mixins import AuthorAccessMixin
# Views
class ArticleList(ListView):
    """Demonstrates docstrings and does nothing really."""
    queryset = Article.objects.published()
    paginate_by = 3


class ArticleDetail(DetailView):
    """Demonstrates docstrings and does nothing really."""
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(Article.objects.published(), slug=slug)

class ArticlePreview(AuthorAccessMixin, DetailView):
    """Demonstrates docstrings and does nothing really."""
    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(Article, pk=pk)


class CategoryList(ListView):
    """Demonstrates docstrings and does nothing really."""
    paginate_by = 2
    template_name = 'blog/category_list.html'

    def get_queryset(self):
        global category 
        slug = self.kwargs.get('slug')
        category = get_object_or_404(Category.objects.active(), slug=slug)
        return category.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = category
        return context


class AuthorList(ListView):
    """Demonstrates docstrings and does nothing really."""
    paginate_by = 2
    template_name = 'blog/author_list.html'

    def get_queryset(self):
        global author 
        username = self.kwargs.get('username')
        author = get_object_or_404(User, username=username)
        return author.articles.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = author
        return context

templates/blog/Article_Detail.html
{% extends 'blog/base.html' %}
{% block title %} | {{article.title}} {% endblock %}
{% block main %}
 <!-- بخش اصلی -->
 <div class="container">
    <div class="row ">
        <div class="col-12">
            <div class="box-abt">
                    <section class="s-post s-one-post">
                        <div class="img-one-post" style=" background-image: url('{{article.thumbnail.url}}')">
                            <h2>{{article.title}}</h2>
                        </div>
                        <div class="tags">
                            <a href="#" class="nav-post">رویداها</a>
                            <a href="#" class="nav-post">برنامه نویسی</a>
                        </div>
                        <p class="p-one-post">
                            {{article.body|safe}}
                        </p>
                        <div class="ftr-post">
                            <div class="row">
                                <div class="col-12">
                                    <ul>
                                        <li>
                                            <i class="fa fa-user-circle" aria-hidden="true"></i>
                                            {{ article.author.get_full_name }}
                                        </li>
                                        <li>
                                            <i class="fa fa-calendar" aria-hidden="true"></i>
                                            {{article.jpublish}}
                                        </li>
                                        <li>
                                            <i class="fa fa-clock-o" aria-hidden="true"></i>
                                            {{article.jTimepublish}}
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </section>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/blog/Article_list.html
{% extends 'blog/list.html' %}

{% block first_page %}
{% url 'blog:home' %}
{% endblock %}

{% block pervious_page %}
{% url 'blog:home' page_obj.previous_page_number %}
{% endblock %}

{% block current_page %}
{% url 'blog:home' %}page/{{ i }}
{% endblock %}

{% block next_page %}
{% url 'blog:home' page_obj.next_page_number %}
{% endblock %}

{% block end_page %}
{% url 'blog:home' page_obj.paginator.num_pages %}
{% endblock %}

templates/blog/Category_List.html
{% extends 'blog/list.html' %}

{% block first_page %}
{% url 'blog:catelist' category.slug %}
{% endblock %}

{% block pervious_page %}
{% url 'blog:catelist' category.slug page_obj.previous_page_number %}
{% endblock %}

{% block current_page %}
{% url 'blog:catelist' category.slug %}/page/{{ i }}
{% endblock %}

{% block next_page %}
{% url 'blog:catelist' category.slug page_obj.next_page_number %}
{% endblock %}

{% block end_page %}
{% url 'blog:catelist' category.slug page_obj.paginator.num_pages %}
{% endblock %}

templates/blog/author_list.html
{% extends 'blog/list.html' %}


{% block first_page %}
{% url 'blog:author' author.username %}
{% endblock %}

{% block pervious_page %}
{% url 'blog:author' author.username page_obj.previous_page_number %}
{% endblock %}

{% block current_page %}
{% url 'blog:author' author.username %}/page/{{ i }}
{% endblock %}

{% block next_page %}
{% url 'blog:author' author.username page_obj.next_page_number %}
{% endblock %}


{% block end_page %}
{% url 'blog:author' author.username page_obj.paginator.num_pages %}
{% endblock %}

templates/blog/base.html
{% load static %} {% load base_tags %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>رتو وبلاگ {% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css" />
    <link rel="stylesheet" href="{% static 'blog/styles/style.css' %}">

</head>

<body dir="rtl">
    <!-- منوی سایت -->
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-green-1">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon white"></span>
                </button> {% cate %}
                <a class="navbar-brand white" href="{% url 'blog:home'%}">{% title %}</a>
            </div>
        </nav>
    </header>

    {% block main %} {% endblock %}
    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js"></script>
    <script>
        new WOW().init();
    </script>
</body>

</html>

templates/blog/contact.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css"/>
    <link rel="stylesheet" href="styles/style.css">
    <!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="styles/contact-hamburgers.min.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="styles/contact-select.min.css">
    <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="styles/contact-util.css">
        <link rel="stylesheet" type="text/css" href="styles/contact-main.css">
    <!--===============================================================================================-->
</head>

<body dir="rtl">
    <!-- منوی سایت -->
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-green-1">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon white"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link white" href="#">رویدادها</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                آموزش ها
                                <i class="fa fa-chevron-down" aria-hidden="true"></i>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item green-1 font-13" href="#">برنامه نویسی</a>
                                <a class="dropdown-item green-1 font-13" href="#">هک و امنیت</a>
                                <a class="dropdown-item green-1 font-13" href="#">طراحی گرافیک</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link white" href="#">کتابخانه</a>
                        </li>
                    </ul>
                </div>
                <a class="navbar-brand white" href="#">Reto|رضا ترابی</a>
            </div>
        </nav>
    </header>
    <!-- بخش اصلی -->
    <div class="container">
        <div class="row ">
            <div class="col-12">
             
	<div class="contact1">
		<div class="container-contact1">
            <form class="contact1-form validate-form">
				<span class="contact1-form-title">
					سفارش پروژه
				</span>

				<div class="wrap-input1 validate-input" data-validate = "Name is required">
					<input class="input1" type="text" name="name" placeholder="نام">
					<span class="shadow-input1"></span>
				</div>

				<div class="wrap-input1 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
					<input class="input1" type="text" name="email" placeholder="رایانامه">
					<span class="shadow-input1"></span>
				</div>

				<div class="wrap-input1 validate-input" data-validate = "Subject is required">
					<input class="input1" type="text" name="subject" placeholder="موضوع">
					<span class="shadow-input1"></span>
				</div>

				<div class="wrap-input1 validate-input" data-validate = "Message is required">
					<textarea class="input1" name="message" placeholder="پیام"></textarea>
					<span class="shadow-input1"></span>
				</div>

				<div class="container-contact1-form-btn">
					<button class="contact1-form-btn">
						<span>
							فرستادن پیام
							<i class="fa fa-long-arrow-left" aria-hidden="true"></i>
						</span>
					</button>
				</div>
			</form>
            <div class="contact1-pic js-tilt" data-tilt>
				<img src="images/bg-contact.png" alt="IMG">
			</div>
		</div>
	</div>
            </div>
        </div>
    </div>
    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.js"></script>
    <script>
        new WOW().init();
        </script>
</body>

</html>